export const STRING = {
  apiError: 'Không kết nối được với máy chủ',
  login: 'Đăng nhập',
  save: 'Lưu',
  confirm: 'Xác nhận',
  cancel: 'Hủy',
  username: 'Tên đăng nhập',
  password: 'Mật khẩu',
  rememberPwd: 'Ghi nhớ đăng nhập',
  expressTimeOut: 'Phiên đăng nhập hết hạn, vui lòng đăng nhập lại',
  picture: 'Hình ảnh',
  signUp: {
    signUp: 'Đăng ký',
    phoneNumber: 'Số điện thoại',
    fullName: 'Họ và tên',
  },
  changePwd: {
    newPwd: 'Mật khẩu mới',
    inputNewPwd: 'Nhập vào mật khẩu mới',
    currentPwd: 'Mật khẩu cũ',
    inputCurrentPwd: 'Nhập vào mật khẩu cũ',
    confirmPwd: 'Xác nhận mật khẩu mới',
    changePwdFistTime: 'Đổi mật khẩu lần đầu',
    changePwd: 'Đổi mật khẩu',
    reLogin: 'Đổi mật khẩu thành công, vui lòng đăng nhập lại!',
    changePwdSucces:
      'Đổi mật khẩu thành công, bạn có muốn lưu lại mật khẩu mới?',
  },
  bottomBar: {
    delivery: 'Giao hàng',
    history: 'Lịch sử',
    dashboard: 'Thống kê',
    profile: 'Cá nhân',
  },
  form: {
    plhTextInput: 'Nhập nội dung',
  },
  valid: {
    notBeBlank: 'không được bỏ trống',
    length: 'Tối thiểu 8 ký tự',
    nonSpecialChar: 'Không được chứa ký tự đặc biệt',
    specialChar: 'Phải chứa ký tự đặc biệt',
    uppercaseChar: 'Ít nhất 1 ký tự viết hoa',
    lowercaseChar: 'Ít nhất 1 ký tự viết thường',
    pwdNotMatch: 'Mật khẩu nhập lại không khớp',
    numberChar: 'Ít nhất 1 ký tự số',
    plsInputQuanti: 'Vui lòng nhập số lượng',
    invalidQuanti: 'Số lượng không hợp lệ',
    numberMustBeInt: 'Vui lòng nhập số nguyên',
    orderStatusInvalid: 'Trạng thái đơn hàng không hợp lệ',
  },
  delivery: {
    hello: 'Xin chào',
    shipment: 'Vận đơn',
    todayWork: 'Công việc hôm nay',
    productHandover: 'Hàng hóa đang giữ',
    materialsHandover: 'Bao bì (khay, vỉ) đang giữ',
    totalRecord: 'SL đơn hàng',
    noReShippingOrder: 'SL đơn hủy/giao lại',
    noReCollectOrder: 'SL đơn hủy/lấy lại',
    noProcessedOrder: 'SL đơn xử lý thành công',
    noInProcessOrder: 'SL đơn đang xử lý',
    deliveryPoint: 'Điểm xuất hàng',
    handOver: 'Bàn giao',
    delivery: 'Giao hàng',
    startShipping: 'Bắt đầu giao hàng',
    startHandover: 'Bàn giao hàng hóa',
    customer: 'Người nhận',
    customerInfor: 'Thông tin đơn hàng',
    deliveryAddress: 'Địa chỉ',
    reason: 'Lý do',
    shipmentPoint: 'Điểm xuất hàng',
    dateReHanover: 'Ngày lấy lại',
    dateReDeliver: 'Ngày giao lại',
    warnignHandover: 'Bàn giao hàng hoá, vận đơn sẽ được cập nhật trạng thái hoàn thành. Bạn chắc chắn muốn thực hiện không?',
  },
  status: {
    waitingForProcess: 'Chờ xử lý',
    inProcess: 'Đang xử lý',
    processed: 'Đã xử lý',

    odWattingDelivery: 'Chờ giao hàng',
    odDelivering: 'Đang giao hàng',
    odDelivered: 'Đã giao hàng',
    odCancelDelivery: 'Huỷ giao',

    odWaitingPickingUp: 'Chờ lấy hàng',
    odPickingUp: 'Đang lấy hàng',
    odPickedUp: 'Đã lấy hàng',
    odCancelPickingUp: 'Huỷ lấy hàng',

    odRedelivery: 'Giao lại',
    odRecover: 'Lấy lại',
  },
  profile: {
    logout: 'Đăng xuất',
    changePwd: 'Đổi mật khẩu',
    appInfor: 'Thông tin ứng dụng',
    deleteAccount: 'Xóa tài khoản',
    deleteAccountNotice: 'Bạn muốn xóa tài khoản?',
    deleteAccountMsg:
      'Tài khoản đã xoá sẽ không thể khôi phục được. Bạn sẽ phải đăng ký tài khoản mới để sử dụng App',
  },
  orderDetail: {
    noMaterial: 'Số sản phẩm',
    materialOffset: 'Hàng bù',
    materialDeliver: 'Bàn giao bao bì (khay, vỉ,...)',
    materialCollect: 'Thu hồi bao bì (khay, vỉ,...)',
  },
  material: {
    total: 'Tổng số lượng đề xuất thu hồi: ',
    quanti: 'Số lượng',
    quantiRecomment: 'Số lượng đề xuất',
    acturalQuanti: 'Số lượng thực thu',

    addMetarialOffset: 'Thêm loại hàng bù',
    addBBLCDelivery: 'Thêm bao bì',
    addBBLCCollect: 'Thêm bao bì',
    metarialOffsetName: 'Mã hàng bù - Tên hàng bù',
    metarialOffsetQuanti: 'Số lượng',

    packaging: 'Bao bì',
    addPackaging: 'Thêm loại bao bì',
    packagingName: 'Mã bao bì - Tên bao bì',
    packagingDeliverQuanti: 'Số lượng',
    packagingCollectQuanti: 'Số lượng',
  },
  product: {
    quanti: 'SL',
    unit: 'Đơn vị',
    code: 'Mã sp',
    deliverQuanti: 'SL thực giao',
    warning: 'Lưu ý: ',
    warQuanti: 'SL thực giao đang lớn hơn số lượng đề xuất',
    invalidQuanti: 'SL không hợp lệ',
    errQuanti: 'Số lượng sản phẩm thực giao không được bỏ trống',
    quantiIs0:'Nhập số lượng sản phẩm bằng 0, đồng nghĩa với sản phẩm này không được giao/lấy'
  },
  btn: {
    save: 'Lưu',
    comfirm: 'Xác nhận',
    touchMe: 'Chọn nội dung',
    choiceReasonHold: 'Chọn lý do tạm giữ',
    delivered: 'Hoàn thành',
    pickedUp: 'Hoàn thành',
    order: 'đơn',
    hold: 'Tạm giữ',
    reTakePicture: 'Chụp lại',
    cancelDeliver: 'Hủy giao hàng',
    cancelHandover: 'Hủy lấy hàng',
    deliverAppointment: 'Hẹn giao lại',
    handoverAppointment: 'Hẹn lấy lại',
    reset: 'Đặt lại',
    showResult: 'Hiện kết quả',
  },
  detentions: {
    cancelDeliver: 'Hủy giao hàng',
    cancelHandover: 'Hủy lấy hàng',
    deliverAppointment: 'Hẹn giao lại',
    handoverAppointment: 'Hẹn lấy lại',
    choiseDateReHanover: 'Chọn ngày lấy lại',
    choiseDateReDeliver: 'Chọn ngày giao lại',
    reason: 'Lý do',
  },
  popup: {
    notice: 'Thông báo',
    error: 'Lỗi',
    success: 'Thành công',
  },
  fillter: {
    title: 'Bộ lọc',
    fromDate: 'Từ ngày',
    from: 'Từ',
    to: 'Đến',
    toDate: 'Đến ngày',
    date: 'Ngày giao hàng',
    code: 'Số vận đơn (Shipment)',
    valid: 'Vui lòng nhập đủ thông tin "Từ ngày", "Đến ngày"',
  },
  empty: {
    haveNoShipment: 'Bạn chưa có vận đơn cần xử lý trong hôm nay',
    haveFinishShipmentYet:
      'Bạn cần hoàn thành xong tất cả các lệnh giao hàng trong vận đơn',
    haveNoShipmentHandover: 'Hiện tại chưa có vận đơn cần bàn giao',
    shipmentHaveNoOrder: 'Vận đơn không được gắn lệnh giao hàng',
    orderHaveNoProduct: 'Lệnh giao hàng hiện không có sản phẩm nào',
    haveNoMaterialOffset:
      'Bạn cần nhập hàng bù thực tế giao cho khách hàng (Nếu có)',
    haveNoMaterialDeliver:
      'Bạn chưa nhập mã và số lượng bao bì cần bàn giao cho khách',
    haveNoMaterialCollect:
      'Bạn chưa nhập mã và số lượng bao bì thực tế cần thu hồi (nếu có)',
    haveNoShipmentHistory: 'Không có dữ liệu lịch sử vận đơn',
    default: 'Không có dữ liệu',
  },
  permission: {
    default: 'Bạn không có quyền thực hiện chức năng này',
    orderSelect: 'Bạn không có quyền xem chi tiết đơn hàng',
    orderUpdate: 'Bạn không có quyền cập nhật đơn hàng',
    startShipmentBefore:
      'Vui lòng chọn "Bắt đầu giao hàng" trước khi xem chi tiết đơn hàng',
    handoverShipmentBefore:
      'Vui lòng chọn "Bàn giao hàng hóa" trước khi xem chi tiết đơn hàng',
  },
};
